# Generated by Django 4.2.3 on 2023-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstelegram',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
