# Generated by Django 4.2.3 on 2023-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='img',
            field=models.ImageField(upload_to='img/weapons/%Y-%m-%d/'),
        ),
    ]
