# Generated by Django 4.2.3 on 2023-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_alter_weapons_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='leg',
            field=models.CharField(choices=[('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary'), ('A', 'Arcane')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
