# Generated by Django 4.2.3 on 2023-07-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_weapons_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='stattrak',
            field=models.BooleanField(default=False),
        ),
    ]
