# Generated by Django 4.2.3 on 2023-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_weapons_stattrak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons',
            name='leg',
            field=models.CharField(choices=[('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary'), ('A', 'Arcane')], max_length=1, verbose_name='Редкость оружия'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='stattrak',
            field=models.BooleanField(default=False, verbose_name='StatTrak'),
        ),
    ]
