# Generated by Django 4.2.3 on 2023-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оружия')),
                ('model_w', models.CharField(max_length=200, verbose_name='Модель оружия')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('weapons', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
