# Generated by Django 4.2.3 on 2023-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_delete_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='img',
            field=models.ImageField(upload_to='img/case/%Y-%m-%d/'),
        ),
    ]
