# Generated by Django 4.2.3 on 2023-07-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='model_w',
        ),
    ]
