# Generated by Django 4.2.3 on 2023-08-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_model_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('position', models.IntegerField()),
                ('cases_arr', models.JSONField()),
            ],
        ),
    ]
